//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProfilerHealthMonitor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiniProfilerEntities : DbContext
    {
        public MiniProfilerEntities()
            : base("name=MiniProfilerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MiniProfiler> MiniProfilers { get; set; }
        public virtual DbSet<MiniProfilerSqlTiming> MiniProfilerSqlTimings { get; set; }
        public virtual DbSet<MiniProfilerTiming> MiniProfilerTimings { get; set; }
        public virtual DbSet<MiniProfilerClientTiming> MiniProfilerClientTimings { get; set; }
        public virtual DbSet<MiniProfilerSqlTimingParameter> MiniProfilerSqlTimingParameters { get; set; }
    }
}
