//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProfilerHealthMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiniProfilerClientTiming
    {
        public System.Guid MiniProfilerId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Start { get; set; }
        public Nullable<decimal> Duration { get; set; }
    }
}
