//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProfilerHealthMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiniProfiler
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Started { get; set; }
        public string MachineName { get; set; }
        public string User { get; set; }
        public Nullable<byte> Level { get; set; }
        public Nullable<System.Guid> RootTimingId { get; set; }
        public decimal DurationMilliseconds { get; set; }
        public Nullable<decimal> DurationMillisecondsInSql { get; set; }
        public bool HasSqlTimings { get; set; }
        public bool HasDuplicateSqlTimings { get; set; }
        public bool HasTrivialTimings { get; set; }
        public bool HasAllTrivialTimings { get; set; }
        public Nullable<decimal> TrivialDurationThresholdMilliseconds { get; set; }
        public bool HasUserViewed { get; set; }
    }
}
